### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by bajere** [ryanolsonk/HeatMapDemo#1]
Hi,

Im looking for a heatmap and found this via Google, looks great, but I would like to run this with lat/lng's from a JSON call. Is that doable with your code base? Sorry if its a stupid question/obvious one, but i'm not an iOS dev, i'm a frontend dev trying to learn some iOS and build a native app...

**Comment by ryanolsonk** [comment]
Hi,

The API for the library does not have direct support for JSON data, but you can easily parse JSON into the format that the library can handle. Check out the example project which parses a CSV file and puts it into an NSDictionary with the proper format: https://github.com/ryanolsonk/HeatMapDemo/blob/master/HeatMapExample/HeatMapViewController.m#L76

The iOS SDK includes the NSJSONSerialization class for parsing JSON: https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSJSONSerialization_Class/Reference/Reference.html

If you want to extend the API of the the library to accept JSON, that would be great! Feel free to open a pull request.
